### ISSUE TITLE
Progress button doesn't appear on SG and Steam Store after put the game ID.

### ISSUE THREAD

**Issue by kaiohpj** [Gaffi/SG-WL-Inventory#13]
**Heres the log output from Chrome console from SG:**

include.preload.js:425 Calling Element.createShadowRoot() for an element which already hosts a shadow root is deprecated. See https://www.chromestatus.com/features/4668884095336448 for more details.
VM744:74 Injecting SteamGifts
VM744:118 Creating button/progress bar on SteamGifts...
VM744:126 Whitelist inventory button loaded without errors.
VM744:133 Last updated: null - Needs to be updated if last updated before: Tue Sep 13 2016 12:12:31 GMT-0300 (Hora oficial do Brasil)
VM744:171 Scanning 22 total whitelisted users for game 360170
VM744:461 Scanning WL [https://www.steamgifts.com/account/manage/whitelist/search?page=1] for user list

**Here's from Steam Store:**

include.preload.js:425Calling Element.createShadowRoot() for an element which already hosts a shadow root is deprecated. See https://www.chromestatus.com/features/4668884095336448 for more details.
enhancedsteam.js:4  Enhanced Steam v8.8 by jshackles  http://www.enhancedsteam.com 
(index):1 GET http://store.akamai.steamstatic.com/public/shared/images/sharedfiles/bg_shared_item_guide.jpg 404 (Not Found)
VM537:70 Injecting Steam Store
VM537:87 Creating button/progress bar on Steam store...
VM537:190 Checking WL page [https://www.steamgifts.com/account/manage/whitelist] for user count.
VM537:101 Whitelist inventory button loaded without errors.
www-widgetapi.js:100 Failed to execute 'postMessage' on 'DOMWindow': The target origin provided ('https://www.youtube.com') does not match the recipient window's origin ('http://store.steampowered.com').g.C @ www-widgetapi.js:100g.H @ www-widgetapi.js:97
www-embed-player.js:222 GET https://googleads.g.doubleclick.net/pagead/id net::ERR_BLOCKED_BY_CLIENTUd @ www-embed-player.js:222Yd @ www-embed-player.js:225(anonymous function) @ www-embed-player.js:1251Eg @ www-embed-player.js:389zq @ www-embed-player.js:1250(anonymous function) @ www-embed-player.js:1302(anonymous function) @ qEIuzobwgZ8?enablejsapi=1&origin=http%3A%2F%2Fstore.steampowered.com&widgetid=1:10
www-embed-player.js:141 GET https://static.doubleclick.net/instream/ad_status.js net::ERR_BLOCKED_BY_CLIENTEc @ www-embed-player.js:141Bc @ www-embed-player.js:138yc @ www-embed-player.js:137ie @ www-embed-player.js:237(anonymous function) @ www-embed-player.js:1304(anonymous function) @ qEIuzobwgZ8?enablejsapi=1&origin=http%3A%2F%2Fstore.steampowered.com&widgetid=1:10
VM537:133 Last updated: null - Needs to be updated if last updated before: Tue Sep 13 2016 12:14:01 GMT-0300 (Hora oficial do Brasil)
VM537:171 Scanning 22 total whitelisted users for game 360170
VM537:461 Scanning WL [https://www.steamgifts.com/account/manage/whitelist/search?page=1] for user list

**Comment by Gaffi** [comment]
Found and will be correcting the problem shortly. Thanks for the catch!
