### ISSUE TITLE
Number Of People Listed In White List Incorrect

### ISSUE THREAD

**Issue by ShandyAndy** [Gaffi/SG-WL-Inventory#3]
I have 99 people in my white list

The popup box I get says:

[Screenshot](https://dl.dropboxusercontent.com/u/15744536/CheckGameOwnership_Issue_2.png)

**Comment by Gaffi** [comment]
I had that issue in testing, made some changes, and cleared it on my end. It seems I may have missed something. I'll see what I can do to fix that. Thanks!

**Comment by ShandyAndy** [comment]
Additional info

The number it finds for white listed users varies each time I click on the button - maybe a timeout issue?

**Comment by Gaffi** [comment]
Related, probably. The code scans multiple WL pages at once, and the summary can pop up before they are all done. I added a timer to wait based on the number of pages, but if your connection is slower (like mine is right now with a big download), then you are more likely to have a problem. There are probably better ways to deal with this, but I've got to figure out what those are first.

**Comment by ShandyAndy** [comment]
I can confirm, I'm currently downloading Space Engineers :)

**Comment by Gaffi** [comment]
Found a better solution, works regardless of WL size and connection speed. Will be posted in next update!
